<?php


require_once('/etc/mica/profiles/mica_distribution/modules/mica/extensions/mica_studies/mica_studies.module');

require_once('/etc/mica/sites/all/modules/interconnect_studies/interconnect_studies.features.inc');


/**
 * Implements hook_form_alter
 * To add dependent fields when filling out the form
 */
function interconnect_studies_form_alter(&$form, &$form_state, $form_id) {

  	 
  switch ($form_id) {
    case 'study_node_form':
		interconnect_studies_study_form_alter($form, $form_state, $form_id);
	break;
    case 'population_node_form':
      interconnect_studies_population_form_alter($form, $form_state, $form_id);
    break;
    case 'data_collection_event_node_form':
      interconnect_studies_data_collection_event_form_alter($form, $form_state, $form_id);
    break;
  }

}

function interconnect_studies_study_form_alter(&$form, &$form_state, $form_id) {
  
    //$form['#validate'][] = '_interconnect_studies_validate';
   
     $form['actions']['_mica_studies_save_add_population_submit'] = array(
    '#access' => TRUE,
    '#value' => t('Save & Add Sampling Frame'),
    '#weight' => 6,
    '#type' => 'submit',
    '#submit' => array('node_form_submit', '_mica_studies_save_add_population_submit'),
  );
   
   
    $form['#groups']['group_general_info']->parent_name = '';
    $form['#groups']['group_methods']->parent_name = ''; 
	$form['#groups']['group_marker_paper']->parent_name = '';
	
	unset($form['#group_children']['group_general_info']);
	unset($form['#group_children']['group_methods']);
	unset($form['#group_children']['group_marker_paper']);
			
	$form['#groups']['group_general_info']->format_settings['formatter'] = 'open';
	$form['#groups']['group_methods']->format_settings['formatter'] = 'open';
	$form['#groups']['group_marker_paper']->format_settings['formatter'] = 'open';
	
$form['#groups']['group_access']->format_type = 'hidden';
$form['#groups']['group_authorization_maelstrom']->format_type = 'hidden';
$form['#groups']['group_authorization_specific']->format_type = 'hidden';
$form['#groups']['group_authorization']->format_type = 'hidden';
$form['#groups']['group_datasets']->format_type = 'hidden';
$form['#groups']['group_documents']->format_type = 'hidden';
$form['#groups']['group_institution']->format_type = 'hidden';
$form['#groups']['group_methods']->format_type = 'hidden';
$form['#groups']['group_nb_participants']->format_type = 'hidden';
$form['#groups']['group_pop_age']->format_type = 'hidden';
$form['#groups']['group_study_name']->format_type = 'hidden';
$form['#groups']['group_study_timeline']->format_type = 'hidden';
$form['#groups']['group_supp_info']->format_type = 'hidden';
$form['#groups']['group_target_nb_participants']->format_type = 'hidden';
$form['#groups']['group_target_nb_samples']->format_type = 'hidden';


	 
$form['body']['#type'] = 'hidden';
$form['field_access_biosamples']['#type'] = 'hidden';
$form['field_access_data']['#type'] = 'hidden';
$form['field_access_other']['#type'] = 'hidden';
$form['field_access_other_sp']['#type'] = 'hidden';
$form['field_address']['#type'] = 'hidden';
$form['field_authorising_date']['#type'] = 'hidden';
$form['field_authorising_date_m']['#type'] = 'hidden';
$form['field_authorising_person_name']['#type'] = 'hidden';
$form['field_authorising_person_name_m']['#type'] = 'hidden';
$form['field_authorization_maelstrom']['#type'] = 'hidden';
$form['field_authorization_specific']['#type'] = 'hidden';
$form['field_city']['#type'] = 'hidden';
$form['field_contact_country']['#type'] = 'hidden';
$form['field_contact_email']['#type'] = 'hidden';
$form['field_contact_name']['#type'] = 'hidden';
$form['field_department_unit']['#type'] = 'hidden';
$form['field_design']['#type'] = 'hidden';
$form['field_design_other_sp']['#type'] = 'hidden';
$form['field_documents']['#type'] = 'hidden';
$form['field_files']['#type'] = 'hidden';
$form['field_info_design_follow_up']['#type'] = 'hidden';
$form['field_institution_name']['#type'] = 'hidden';
$form['field_investigators']['#type'] = 'hidden';
$form['field_logo']['#type'] = 'hidden';
$form['field_no_limits_participants']['#type'] = 'hidden';
$form['field_no_limits_samples']['#type'] = 'hidden';
$form['field_postal_code']['#type'] = 'hidden';
$form['field_recruitment']['#type'] = 'hidden';
$form['field_recruitment_other_sp']['#type'] = 'hidden';
$form['field_recruitment_supp_info']['#type'] = 'hidden';
$form['field_state']['#type'] = 'hidden';
$form['field_study_end_year']['#type'] = 'hidden';
$form['field_study_start_year']['#type'] = 'hidden';
$form['field_study_study_variable_att']['#type'] = 'hidden';
$form['field_supp_infos']['#type'] = 'hidden';
$form['field_target_nb_supp_info']['#type'] = 'hidden';
$form['field_target_number_biosamples']['#type'] = 'hidden';
$form['field_target_number_participants']['#type'] = 'hidden';
$form['field_telephone']['#type'] = 'hidden';
$form['mica_dataset']['#type'] = 'hidden';
$form['mica_opal']['#type'] = 'hidden';

  
  // move study ref paper fields into general info
   
  $form['#group_children']['group_marker_paper'] = 'group_general_info';
  $form['#groups']['group_marker_paper']->weight = '5';
  $form['#groups']['group_marker_paper']->format_type = 'fieldset';
  $form['#groups']['group_marker_paper']->format_settings['formatter'] = 'open';

// adjust the weights of other fields

  $form['#group_children']['field_dna_ic'] = 'group_general_info';
  $form['field_dna_ic']['#weight'] = '7';

  
// move the new study design fields into the right group

  $form['#group_children']['field_b_line_rec_start_ic'] = 'group_study_design';
  $form['field_b_line_rec_start_ic']['#weight'] = '1';
  
  $form['#group_children']['field_b_line_rec_status_ic'] = 'group_study_design';
  $form['field_b_line_rec_status_ic']['#weight'] = '2';
  
  $form['#group_children']['field_b_line_rec_end_ic'] = 'group_study_design';
  $form['field_b_line_rec_end_ic']['#weight'] = '3';
  
  $form['#group_children']['field_number_of_participants_ic'] = 'group_study_design';
  $form['field_number_of_participants_ic']['#weight'] = '4';

  $form['#group_children']['field_participants_date_ic'] = 'group_study_design';
  $form['field_participants_date_ic']['#weight'] = '5';

  $form['#group_children']['field_follow_up_ic'] = 'group_study_design';
  $form['field_follow_up_ic']['#weight'] = '6';
  
  $form['#group_children']['field_follow_up_date_ic'] = 'group_study_design';
  $form['field_follow_up_date_ic']['#weight'] = '7';  

  $form['#group_children']['field_design_ic'] = 'group_study_design';
  $form['field_design_ic']['#weight'] = '10'; 
  
  $form['#group_children']['field_outcomes_ic'] = 'group_study_design';
  $form['field_outcomes_ic']['#weight'] = '11';
  
  $form['#group_children']['field_oc_other_pr_diabetes_ic'] = 'group_study_design';
  $form['field_oc_other_pr_diabetes_ic']['#weight'] = '12';
  
  $form['#group_children']['field_oc_other_inc_diabetes_ic'] = 'group_study_design';
  $form['field_oc_other_inc_diabetes_ic']['#weight'] = '13';
  
  $form['#group_children']['field_prev_disease_ic'] = 'group_study_design';
  $form['field_prev_disease_ic']['#weight'] = '11';
  
  $form['#group_children']['field_other_pr_diabetes_ic'] = 'group_study_design';
  $form['field_other_pr_diabetes_ic']['#weight'] = '12';

  $form['#group_children']['field_case_definition_ic'] = 'group_study_design';
  $form['field_case_definition_ic']['#weight'] = '11'; 

  $form['#group_children']['field_interv_type_ic'] = 'group_study_design';
  $form['field_interv_type_ic']['#weight'] = '14';
  
  $form['#group_children']['field_interv_other_ic'] = 'group_study_design';
  $form['field_interv_other_ic']['#weight'] = '15';  
  
  //set up dependent fields for study design
  
$options = array(
	'case_control',
	'case_only',
	'clinical_trial',
	'cohort_study',
	'cross_sectional',
	'other',
	'_none'
	);
	$form['field_design_ic']['und']['#default_value'] = '_none';
	
	
$visible_options = array(
		'clinical_trial',
	'cohort_study');
	
   _double_simple($form, 'field_design_ic', 'field_outcomes_ic', $options, $visible_options);
   _mica_add_dependent_field_checked($form, 'field_outcomes_ic', 'field_oc_other_pr_diabetes_ic', 'OD_p');
   _mica_add_dependent_field_checked($form, 'field_outcomes_ic', 'field_oc_other_inc_diabetes_ic', 'OD_i');
   
// clinical trial only   
   
   _mica_add_dependent_field_checked($form, 'field_design_ic', 'field_interv_type_ic', 'clinical_trial');
   _mica_add_dependent_field_checked($form, 'field_interv_type_ic', 'field_interv_other_ic', 'other');   
	
// cross sectional trial only   

  _mica_add_dependent_field_checked($form, 'field_design_ic', 'field_prev_disease_ic', 'cross_sectional');
  _mica_add_dependent_field_checked($form, 'field_prev_disease_ic', 'field_other_pr_diabetes_ic', 'other');

// case control only

  _mica_add_dependent_field_checked($form, 'field_design_ic', 'field_num_cases_ic', 'case_control');
   _mica_add_dependent_field_checked($form, 'field_design_ic', 'field_num_controls_ic', 'case_control');

    $visible_options = array(
		'case_control',
	'case_only');
  _double_simple($form, 'field_design_ic', 'field_case_definition_ic', $options, $visible_options);
  _mica_add_dependent_field_checked($form, 'field_case_definition_ic', 'field_other_pr_diabetes_ic', 'other');

dpm($form, $name = NULL);

}

function interconnect_studies_population_form_alter(&$form, &$form_state, $form_id) {
	
	// hide old recruitment field
  $form['field_pop_src_recruit']['#type'] = 'hidden';
	
	// use new recruitment fields
	
  $form['#group_children']['field_sources_of_recruitment'] = 'group_pop_recruitment_procedures';
  $form['field_sources_of_recruitment']['#weight'] = '10';
  
  $form['#group_children']['field_participants_from_existing'] = 'group_pop_recruitment_procedures';
  $form['field_participants_from_existing']['#weight'] = '11';
  
   $form['field_pop_specific_pop']['#weight'] = '10'; 

   // hide Supplementary information about recruitment procedures 
   $form['field_pop_recruit_supp_info']['#type'] = 'hidden';
   
	//hide general population recruitment field and supp info
	
	$form['field_pop_general_pop_recruit']['#type'] = 'hidden';
	$form['field_recruitment_supp_info']['#type'] = 'hidden';

 
   	//hide territory or city of residence field
	
	$form['field_pop_territory']['#type'] = 'hidden';
   	
	//hide old pregnancy field
	$form['field_pop_select_criteria']['#type'] = 'hidden';	
	
	// add pregnant women field to selection criteria

	$form['#group_children']['field_pregnancy'] = 'group_pop_selection_criteria';
    $form['field_pregnancy']['#weight'] = '6';

	//hide health status field
	$form['field_pop_health_status']['#type'] = 'hidden';		

	//hide recruitment procedure supplementary info field
	$form['field_pop_partcipant_sel_supp_in']['#type'] = 'hidden';
   
  // move ic recruitment target fields to general info group
  
    $form['#group_children']['field_recruitment_target_ic'] = 'group_general_info';
	$form['field_recruitment_target_ic']['#weight'] = '4';
	$form['#group_children']['field_other_recruitment_targ_ic'] = 'group_general_info';
	$form['field_other_recruitment_targ_ic']['#weight'] = '5';
	
	//move group_pop_selection_criteria to 2nd position
	
	$form['#groups']['group_pop_selection_criteria']->weight = '1';
	
	//ancestries
	
	$form['#groups']['group_ancestries']->parent_name = 'group_pop_selection_criteria';
	$form['#group_children']['group_ancestries'] = 'group_pop_selection_criteria';
	
	
	$form['field_other_ancestry_spec']['#states'] = array(
      'visible' => array(
        ':input[name="field_other_ancestry[und][0][value]"]' => array('filled' => TRUE),
      ),
    );
	
	// dependent fields
	
  _mica_add_dependent_field_checked($form, 'field_sources_of_recruitment', 'field_pop_specific_pop', 'specific_population');
	
  _mica_add_dependent_field_checked($form, 'field_participants_from_existing', 'field_pop_exist_study_part', 'PartEx');

   _mica_add_dependent_field_checked($form, 'field_recruitment_target_ic', 'field_other_recruitment_targ_ic', 'other');

   _mica_add_dependent_field_checked($form, 'field_recruitment_target_ic', 'field_pop_recruitment_other', 'other');
  
   
//dpm($form, $name = NULL);
}

 function _interconnect_studies_validate($node, $form) {

  //dpm($node, $name = NULL);

 debug($node['field_african_african_american_b']['und']['0']['value']['#value']); 

 $total = $node['field_african_african_american_b']['und']['0']['value']['#value'] + $node['field_caucasian_european_white']['und']['0']['value']['#value']
			+ $node['field_asian_native_american']['und']['0']['value']['#value'] + $node['field_other_ancestry']['und']['0']['value']['#value'];
 debug($total);

if($total != 100){
    form_set_error('title', 'The ancestries must sum to 100% ');
    
}

}



function _double_simple(&$form, $dependee, $dependent, $options, $visible_options) {
	$lang = $form[$dependee]['#language'];
	$input = ':input[name="' . $dependee . '[' . $lang . ']"]';
	foreach (array_diff($options, $visible_options) as $i => $vocab) {
	$form[$dependent]['#states']['visible'][$input . ', my-nonsense-dummy-element-' . $i] =
		array('!value' => $vocab);

		}
}

