<?php
/**
 * @file
 * interconnect_studies.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function interconnect_studies_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'create field_african_mds_plots_ic'.
  $permissions['create field_african_mds_plots_ic'] = array(
    'name' => 'create field_african_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_e_asian_mds_plots_ic'.
  $permissions['create field_e_asian_mds_plots_ic'] = array(
    'name' => 'create field_e_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_euro_mds_plots_ic'.
  $permissions['create field_euro_mds_plots_ic'] = array(
    'name' => 'create field_euro_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_gen_array_ic'.
  $permissions['create field_gen_array_ic'] = array(
    'name' => 'create field_gen_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_african_ic'.
  $permissions['create field_genotype_african_ic'] = array(
    'name' => 'create field_genotype_african_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_east_asian_ic'.
  $permissions['create field_genotype_east_asian_ic'] = array(
    'name' => 'create field_genotype_east_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_euro_ic'.
  $permissions['create field_genotype_euro_ic'] = array(
    'name' => 'create field_genotype_euro_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_his_lat_ic'.
  $permissions['create field_genotype_his_lat_ic'] = array(
    'name' => 'create field_genotype_his_lat_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_indig_am_ic'.
  $permissions['create field_genotype_indig_am_ic'] = array(
    'name' => 'create field_genotype_indig_am_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_indig_aus_ic'.
  $permissions['create field_genotype_indig_aus_ic'] = array(
    'name' => 'create field_genotype_indig_aus_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_indig_pac_ic'.
  $permissions['create field_genotype_indig_pac_ic'] = array(
    'name' => 'create field_genotype_indig_pac_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_mid_e_ic'.
  $permissions['create field_genotype_mid_e_ic'] = array(
    'name' => 'create field_genotype_mid_e_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_num_indv_ic'.
  $permissions['create field_genotype_num_indv_ic'] = array(
    'name' => 'create field_genotype_num_indv_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_other_ic'.
  $permissions['create field_genotype_other_ic'] = array(
    'name' => 'create field_genotype_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotype_south_asian_ic'.
  $permissions['create field_genotype_south_asian_ic'] = array(
    'name' => 'create field_genotype_south_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotyping_array_ic'.
  $permissions['create field_genotyping_array_ic'] = array(
    'name' => 'create field_genotyping_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_genotyping_platform'.
  $permissions['create field_genotyping_platform'] = array(
    'name' => 'create field_genotyping_platform',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_his_lat_mds_plots_ic'.
  $permissions['create field_his_lat_mds_plots_ic'] = array(
    'name' => 'create field_his_lat_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_imp_panel_release_date_ic'.
  $permissions['create field_imp_panel_release_date_ic'] = array(
    'name' => 'create field_imp_panel_release_date_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_imputation_panel'.
  $permissions['create field_imputation_panel'] = array(
    'name' => 'create field_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_imputation_panel_ic'.
  $permissions['create field_imputation_panel_ic'] = array(
    'name' => 'create field_imputation_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_impute_panel_ic'.
  $permissions['create field_impute_panel_ic'] = array(
    'name' => 'create field_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_indig_am_mds_plots_ic'.
  $permissions['create field_indig_am_mds_plots_ic'] = array(
    'name' => 'create field_indig_am_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_indig_aus_mds_plots_ic'.
  $permissions['create field_indig_aus_mds_plots_ic'] = array(
    'name' => 'create field_indig_aus_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_indig_pac_mds_plots_ic'.
  $permissions['create field_indig_pac_mds_plots_ic'] = array(
    'name' => 'create field_indig_pac_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_mid_e_mds_plots_ic'.
  $permissions['create field_mid_e_mds_plots_ic'] = array(
    'name' => 'create field_mid_e_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_number_of_individuals'.
  $permissions['create field_number_of_individuals'] = array(
    'name' => 'create field_number_of_individuals',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_other_gen_arrays_ic'.
  $permissions['create field_other_gen_arrays_ic'] = array(
    'name' => 'create field_other_gen_arrays_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_other_imputation_panel'.
  $permissions['create field_other_imputation_panel'] = array(
    'name' => 'create field_other_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_other_impute_panel_ic'.
  $permissions['create field_other_impute_panel_ic'] = array(
    'name' => 'create field_other_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_other_mds_plots_ic'.
  $permissions['create field_other_mds_plots_ic'] = array(
    'name' => 'create field_other_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_other_platforms'.
  $permissions['create field_other_platforms'] = array(
    'name' => 'create field_other_platforms',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_other_reference_population'.
  $permissions['create field_other_reference_population'] = array(
    'name' => 'create field_other_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_pop_ic'.
  $permissions['create field_reference_pop_ic'] = array(
    'name' => 'create field_reference_pop_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_pop_other_ic'.
  $permissions['create field_reference_pop_other_ic'] = array(
    'name' => 'create field_reference_pop_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_reference_population'.
  $permissions['create field_reference_population'] = array(
    'name' => 'create field_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_release_date'.
  $permissions['create field_release_date'] = array(
    'name' => 'create field_release_date',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'create field_s_asian_mds_plots_ic'.
  $permissions['create field_s_asian_mds_plots_ic'] = array(
    'name' => 'create field_s_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_african_mds_plots_ic'.
  $permissions['edit field_african_mds_plots_ic'] = array(
    'name' => 'edit field_african_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_e_asian_mds_plots_ic'.
  $permissions['edit field_e_asian_mds_plots_ic'] = array(
    'name' => 'edit field_e_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_euro_mds_plots_ic'.
  $permissions['edit field_euro_mds_plots_ic'] = array(
    'name' => 'edit field_euro_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_gen_array_ic'.
  $permissions['edit field_gen_array_ic'] = array(
    'name' => 'edit field_gen_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_african_ic'.
  $permissions['edit field_genotype_african_ic'] = array(
    'name' => 'edit field_genotype_african_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_east_asian_ic'.
  $permissions['edit field_genotype_east_asian_ic'] = array(
    'name' => 'edit field_genotype_east_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_euro_ic'.
  $permissions['edit field_genotype_euro_ic'] = array(
    'name' => 'edit field_genotype_euro_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_his_lat_ic'.
  $permissions['edit field_genotype_his_lat_ic'] = array(
    'name' => 'edit field_genotype_his_lat_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_indig_am_ic'.
  $permissions['edit field_genotype_indig_am_ic'] = array(
    'name' => 'edit field_genotype_indig_am_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_indig_aus_ic'.
  $permissions['edit field_genotype_indig_aus_ic'] = array(
    'name' => 'edit field_genotype_indig_aus_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_indig_pac_ic'.
  $permissions['edit field_genotype_indig_pac_ic'] = array(
    'name' => 'edit field_genotype_indig_pac_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_mid_e_ic'.
  $permissions['edit field_genotype_mid_e_ic'] = array(
    'name' => 'edit field_genotype_mid_e_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_num_indv_ic'.
  $permissions['edit field_genotype_num_indv_ic'] = array(
    'name' => 'edit field_genotype_num_indv_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_other_ic'.
  $permissions['edit field_genotype_other_ic'] = array(
    'name' => 'edit field_genotype_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotype_south_asian_ic'.
  $permissions['edit field_genotype_south_asian_ic'] = array(
    'name' => 'edit field_genotype_south_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotyping_array_ic'.
  $permissions['edit field_genotyping_array_ic'] = array(
    'name' => 'edit field_genotyping_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_genotyping_platform'.
  $permissions['edit field_genotyping_platform'] = array(
    'name' => 'edit field_genotyping_platform',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_his_lat_mds_plots_ic'.
  $permissions['edit field_his_lat_mds_plots_ic'] = array(
    'name' => 'edit field_his_lat_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_imp_panel_release_date_ic'.
  $permissions['edit field_imp_panel_release_date_ic'] = array(
    'name' => 'edit field_imp_panel_release_date_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_imputation_panel'.
  $permissions['edit field_imputation_panel'] = array(
    'name' => 'edit field_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_imputation_panel_ic'.
  $permissions['edit field_imputation_panel_ic'] = array(
    'name' => 'edit field_imputation_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_impute_panel_ic'.
  $permissions['edit field_impute_panel_ic'] = array(
    'name' => 'edit field_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_indig_am_mds_plots_ic'.
  $permissions['edit field_indig_am_mds_plots_ic'] = array(
    'name' => 'edit field_indig_am_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_indig_aus_mds_plots_ic'.
  $permissions['edit field_indig_aus_mds_plots_ic'] = array(
    'name' => 'edit field_indig_aus_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_indig_pac_mds_plots_ic'.
  $permissions['edit field_indig_pac_mds_plots_ic'] = array(
    'name' => 'edit field_indig_pac_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_mid_e_mds_plots_ic'.
  $permissions['edit field_mid_e_mds_plots_ic'] = array(
    'name' => 'edit field_mid_e_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_number_of_individuals'.
  $permissions['edit field_number_of_individuals'] = array(
    'name' => 'edit field_number_of_individuals',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_other_gen_arrays_ic'.
  $permissions['edit field_other_gen_arrays_ic'] = array(
    'name' => 'edit field_other_gen_arrays_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_other_imputation_panel'.
  $permissions['edit field_other_imputation_panel'] = array(
    'name' => 'edit field_other_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_other_impute_panel_ic'.
  $permissions['edit field_other_impute_panel_ic'] = array(
    'name' => 'edit field_other_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_other_mds_plots_ic'.
  $permissions['edit field_other_mds_plots_ic'] = array(
    'name' => 'edit field_other_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_other_platforms'.
  $permissions['edit field_other_platforms'] = array(
    'name' => 'edit field_other_platforms',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_other_reference_population'.
  $permissions['edit field_other_reference_population'] = array(
    'name' => 'edit field_other_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_pop_ic'.
  $permissions['edit field_reference_pop_ic'] = array(
    'name' => 'edit field_reference_pop_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_pop_other_ic'.
  $permissions['edit field_reference_pop_other_ic'] = array(
    'name' => 'edit field_reference_pop_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_reference_population'.
  $permissions['edit field_reference_population'] = array(
    'name' => 'edit field_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_release_date'.
  $permissions['edit field_release_date'] = array(
    'name' => 'edit field_release_date',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit field_s_asian_mds_plots_ic'.
  $permissions['edit field_s_asian_mds_plots_ic'] = array(
    'name' => 'edit field_s_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_african_mds_plots_ic'.
  $permissions['edit own field_african_mds_plots_ic'] = array(
    'name' => 'edit own field_african_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_e_asian_mds_plots_ic'.
  $permissions['edit own field_e_asian_mds_plots_ic'] = array(
    'name' => 'edit own field_e_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_euro_mds_plots_ic'.
  $permissions['edit own field_euro_mds_plots_ic'] = array(
    'name' => 'edit own field_euro_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_gen_array_ic'.
  $permissions['edit own field_gen_array_ic'] = array(
    'name' => 'edit own field_gen_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_african_ic'.
  $permissions['edit own field_genotype_african_ic'] = array(
    'name' => 'edit own field_genotype_african_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_east_asian_ic'.
  $permissions['edit own field_genotype_east_asian_ic'] = array(
    'name' => 'edit own field_genotype_east_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_euro_ic'.
  $permissions['edit own field_genotype_euro_ic'] = array(
    'name' => 'edit own field_genotype_euro_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_his_lat_ic'.
  $permissions['edit own field_genotype_his_lat_ic'] = array(
    'name' => 'edit own field_genotype_his_lat_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_indig_am_ic'.
  $permissions['edit own field_genotype_indig_am_ic'] = array(
    'name' => 'edit own field_genotype_indig_am_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_indig_aus_ic'.
  $permissions['edit own field_genotype_indig_aus_ic'] = array(
    'name' => 'edit own field_genotype_indig_aus_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_indig_pac_ic'.
  $permissions['edit own field_genotype_indig_pac_ic'] = array(
    'name' => 'edit own field_genotype_indig_pac_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_mid_e_ic'.
  $permissions['edit own field_genotype_mid_e_ic'] = array(
    'name' => 'edit own field_genotype_mid_e_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_num_indv_ic'.
  $permissions['edit own field_genotype_num_indv_ic'] = array(
    'name' => 'edit own field_genotype_num_indv_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_other_ic'.
  $permissions['edit own field_genotype_other_ic'] = array(
    'name' => 'edit own field_genotype_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotype_south_asian_ic'.
  $permissions['edit own field_genotype_south_asian_ic'] = array(
    'name' => 'edit own field_genotype_south_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotyping_array_ic'.
  $permissions['edit own field_genotyping_array_ic'] = array(
    'name' => 'edit own field_genotyping_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_genotyping_platform'.
  $permissions['edit own field_genotyping_platform'] = array(
    'name' => 'edit own field_genotyping_platform',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_his_lat_mds_plots_ic'.
  $permissions['edit own field_his_lat_mds_plots_ic'] = array(
    'name' => 'edit own field_his_lat_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_imp_panel_release_date_ic'.
  $permissions['edit own field_imp_panel_release_date_ic'] = array(
    'name' => 'edit own field_imp_panel_release_date_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_imputation_panel'.
  $permissions['edit own field_imputation_panel'] = array(
    'name' => 'edit own field_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_imputation_panel_ic'.
  $permissions['edit own field_imputation_panel_ic'] = array(
    'name' => 'edit own field_imputation_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_impute_panel_ic'.
  $permissions['edit own field_impute_panel_ic'] = array(
    'name' => 'edit own field_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_indig_am_mds_plots_ic'.
  $permissions['edit own field_indig_am_mds_plots_ic'] = array(
    'name' => 'edit own field_indig_am_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_indig_aus_mds_plots_ic'.
  $permissions['edit own field_indig_aus_mds_plots_ic'] = array(
    'name' => 'edit own field_indig_aus_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_indig_pac_mds_plots_ic'.
  $permissions['edit own field_indig_pac_mds_plots_ic'] = array(
    'name' => 'edit own field_indig_pac_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_mid_e_mds_plots_ic'.
  $permissions['edit own field_mid_e_mds_plots_ic'] = array(
    'name' => 'edit own field_mid_e_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_number_of_individuals'.
  $permissions['edit own field_number_of_individuals'] = array(
    'name' => 'edit own field_number_of_individuals',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_other_gen_arrays_ic'.
  $permissions['edit own field_other_gen_arrays_ic'] = array(
    'name' => 'edit own field_other_gen_arrays_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_other_imputation_panel'.
  $permissions['edit own field_other_imputation_panel'] = array(
    'name' => 'edit own field_other_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_other_impute_panel_ic'.
  $permissions['edit own field_other_impute_panel_ic'] = array(
    'name' => 'edit own field_other_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_other_mds_plots_ic'.
  $permissions['edit own field_other_mds_plots_ic'] = array(
    'name' => 'edit own field_other_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_other_platforms'.
  $permissions['edit own field_other_platforms'] = array(
    'name' => 'edit own field_other_platforms',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_other_reference_population'.
  $permissions['edit own field_other_reference_population'] = array(
    'name' => 'edit own field_other_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_pop_ic'.
  $permissions['edit own field_reference_pop_ic'] = array(
    'name' => 'edit own field_reference_pop_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_pop_other_ic'.
  $permissions['edit own field_reference_pop_other_ic'] = array(
    'name' => 'edit own field_reference_pop_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_reference_population'.
  $permissions['edit own field_reference_population'] = array(
    'name' => 'edit own field_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_release_date'.
  $permissions['edit own field_release_date'] = array(
    'name' => 'edit own field_release_date',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'edit own field_s_asian_mds_plots_ic'.
  $permissions['edit own field_s_asian_mds_plots_ic'] = array(
    'name' => 'edit own field_s_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_african_mds_plots_ic'.
  $permissions['view field_african_mds_plots_ic'] = array(
    'name' => 'view field_african_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_e_asian_mds_plots_ic'.
  $permissions['view field_e_asian_mds_plots_ic'] = array(
    'name' => 'view field_e_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_euro_mds_plots_ic'.
  $permissions['view field_euro_mds_plots_ic'] = array(
    'name' => 'view field_euro_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_gen_array_ic'.
  $permissions['view field_gen_array_ic'] = array(
    'name' => 'view field_gen_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_african_ic'.
  $permissions['view field_genotype_african_ic'] = array(
    'name' => 'view field_genotype_african_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_east_asian_ic'.
  $permissions['view field_genotype_east_asian_ic'] = array(
    'name' => 'view field_genotype_east_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_euro_ic'.
  $permissions['view field_genotype_euro_ic'] = array(
    'name' => 'view field_genotype_euro_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_his_lat_ic'.
  $permissions['view field_genotype_his_lat_ic'] = array(
    'name' => 'view field_genotype_his_lat_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_indig_am_ic'.
  $permissions['view field_genotype_indig_am_ic'] = array(
    'name' => 'view field_genotype_indig_am_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_indig_aus_ic'.
  $permissions['view field_genotype_indig_aus_ic'] = array(
    'name' => 'view field_genotype_indig_aus_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_indig_pac_ic'.
  $permissions['view field_genotype_indig_pac_ic'] = array(
    'name' => 'view field_genotype_indig_pac_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_mid_e_ic'.
  $permissions['view field_genotype_mid_e_ic'] = array(
    'name' => 'view field_genotype_mid_e_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_num_indv_ic'.
  $permissions['view field_genotype_num_indv_ic'] = array(
    'name' => 'view field_genotype_num_indv_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_other_ic'.
  $permissions['view field_genotype_other_ic'] = array(
    'name' => 'view field_genotype_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotype_south_asian_ic'.
  $permissions['view field_genotype_south_asian_ic'] = array(
    'name' => 'view field_genotype_south_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotyping_array_ic'.
  $permissions['view field_genotyping_array_ic'] = array(
    'name' => 'view field_genotyping_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_genotyping_platform'.
  $permissions['view field_genotyping_platform'] = array(
    'name' => 'view field_genotyping_platform',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_his_lat_mds_plots_ic'.
  $permissions['view field_his_lat_mds_plots_ic'] = array(
    'name' => 'view field_his_lat_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_imp_panel_release_date_ic'.
  $permissions['view field_imp_panel_release_date_ic'] = array(
    'name' => 'view field_imp_panel_release_date_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_imputation_panel'.
  $permissions['view field_imputation_panel'] = array(
    'name' => 'view field_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_imputation_panel_ic'.
  $permissions['view field_imputation_panel_ic'] = array(
    'name' => 'view field_imputation_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_impute_panel_ic'.
  $permissions['view field_impute_panel_ic'] = array(
    'name' => 'view field_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_indig_am_mds_plots_ic'.
  $permissions['view field_indig_am_mds_plots_ic'] = array(
    'name' => 'view field_indig_am_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_indig_aus_mds_plots_ic'.
  $permissions['view field_indig_aus_mds_plots_ic'] = array(
    'name' => 'view field_indig_aus_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_indig_pac_mds_plots_ic'.
  $permissions['view field_indig_pac_mds_plots_ic'] = array(
    'name' => 'view field_indig_pac_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_mid_e_mds_plots_ic'.
  $permissions['view field_mid_e_mds_plots_ic'] = array(
    'name' => 'view field_mid_e_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_number_of_individuals'.
  $permissions['view field_number_of_individuals'] = array(
    'name' => 'view field_number_of_individuals',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_other_gen_arrays_ic'.
  $permissions['view field_other_gen_arrays_ic'] = array(
    'name' => 'view field_other_gen_arrays_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_other_imputation_panel'.
  $permissions['view field_other_imputation_panel'] = array(
    'name' => 'view field_other_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_other_impute_panel_ic'.
  $permissions['view field_other_impute_panel_ic'] = array(
    'name' => 'view field_other_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_other_mds_plots_ic'.
  $permissions['view field_other_mds_plots_ic'] = array(
    'name' => 'view field_other_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_other_platforms'.
  $permissions['view field_other_platforms'] = array(
    'name' => 'view field_other_platforms',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_other_reference_population'.
  $permissions['view field_other_reference_population'] = array(
    'name' => 'view field_other_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_pop_ic'.
  $permissions['view field_reference_pop_ic'] = array(
    'name' => 'view field_reference_pop_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_pop_other_ic'.
  $permissions['view field_reference_pop_other_ic'] = array(
    'name' => 'view field_reference_pop_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_reference_population'.
  $permissions['view field_reference_population'] = array(
    'name' => 'view field_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_release_date'.
  $permissions['view field_release_date'] = array(
    'name' => 'view field_release_date',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view field_s_asian_mds_plots_ic'.
  $permissions['view field_s_asian_mds_plots_ic'] = array(
    'name' => 'view field_s_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_african_mds_plots_ic'.
  $permissions['view own field_african_mds_plots_ic'] = array(
    'name' => 'view own field_african_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_e_asian_mds_plots_ic'.
  $permissions['view own field_e_asian_mds_plots_ic'] = array(
    'name' => 'view own field_e_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_euro_mds_plots_ic'.
  $permissions['view own field_euro_mds_plots_ic'] = array(
    'name' => 'view own field_euro_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_gen_array_ic'.
  $permissions['view own field_gen_array_ic'] = array(
    'name' => 'view own field_gen_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_african_ic'.
  $permissions['view own field_genotype_african_ic'] = array(
    'name' => 'view own field_genotype_african_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_east_asian_ic'.
  $permissions['view own field_genotype_east_asian_ic'] = array(
    'name' => 'view own field_genotype_east_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_euro_ic'.
  $permissions['view own field_genotype_euro_ic'] = array(
    'name' => 'view own field_genotype_euro_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_his_lat_ic'.
  $permissions['view own field_genotype_his_lat_ic'] = array(
    'name' => 'view own field_genotype_his_lat_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_indig_am_ic'.
  $permissions['view own field_genotype_indig_am_ic'] = array(
    'name' => 'view own field_genotype_indig_am_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_indig_aus_ic'.
  $permissions['view own field_genotype_indig_aus_ic'] = array(
    'name' => 'view own field_genotype_indig_aus_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_indig_pac_ic'.
  $permissions['view own field_genotype_indig_pac_ic'] = array(
    'name' => 'view own field_genotype_indig_pac_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_mid_e_ic'.
  $permissions['view own field_genotype_mid_e_ic'] = array(
    'name' => 'view own field_genotype_mid_e_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_num_indv_ic'.
  $permissions['view own field_genotype_num_indv_ic'] = array(
    'name' => 'view own field_genotype_num_indv_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_other_ic'.
  $permissions['view own field_genotype_other_ic'] = array(
    'name' => 'view own field_genotype_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotype_south_asian_ic'.
  $permissions['view own field_genotype_south_asian_ic'] = array(
    'name' => 'view own field_genotype_south_asian_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotyping_array_ic'.
  $permissions['view own field_genotyping_array_ic'] = array(
    'name' => 'view own field_genotyping_array_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_genotyping_platform'.
  $permissions['view own field_genotyping_platform'] = array(
    'name' => 'view own field_genotyping_platform',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_his_lat_mds_plots_ic'.
  $permissions['view own field_his_lat_mds_plots_ic'] = array(
    'name' => 'view own field_his_lat_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_imp_panel_release_date_ic'.
  $permissions['view own field_imp_panel_release_date_ic'] = array(
    'name' => 'view own field_imp_panel_release_date_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_imputation_panel'.
  $permissions['view own field_imputation_panel'] = array(
    'name' => 'view own field_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_imputation_panel_ic'.
  $permissions['view own field_imputation_panel_ic'] = array(
    'name' => 'view own field_imputation_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_impute_panel_ic'.
  $permissions['view own field_impute_panel_ic'] = array(
    'name' => 'view own field_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_indig_am_mds_plots_ic'.
  $permissions['view own field_indig_am_mds_plots_ic'] = array(
    'name' => 'view own field_indig_am_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_indig_aus_mds_plots_ic'.
  $permissions['view own field_indig_aus_mds_plots_ic'] = array(
    'name' => 'view own field_indig_aus_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_indig_pac_mds_plots_ic'.
  $permissions['view own field_indig_pac_mds_plots_ic'] = array(
    'name' => 'view own field_indig_pac_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_mid_e_mds_plots_ic'.
  $permissions['view own field_mid_e_mds_plots_ic'] = array(
    'name' => 'view own field_mid_e_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_number_of_individuals'.
  $permissions['view own field_number_of_individuals'] = array(
    'name' => 'view own field_number_of_individuals',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_other_gen_arrays_ic'.
  $permissions['view own field_other_gen_arrays_ic'] = array(
    'name' => 'view own field_other_gen_arrays_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_other_imputation_panel'.
  $permissions['view own field_other_imputation_panel'] = array(
    'name' => 'view own field_other_imputation_panel',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_other_impute_panel_ic'.
  $permissions['view own field_other_impute_panel_ic'] = array(
    'name' => 'view own field_other_impute_panel_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_other_mds_plots_ic'.
  $permissions['view own field_other_mds_plots_ic'] = array(
    'name' => 'view own field_other_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_other_platforms'.
  $permissions['view own field_other_platforms'] = array(
    'name' => 'view own field_other_platforms',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_other_reference_population'.
  $permissions['view own field_other_reference_population'] = array(
    'name' => 'view own field_other_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_pop_ic'.
  $permissions['view own field_reference_pop_ic'] = array(
    'name' => 'view own field_reference_pop_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_pop_other_ic'.
  $permissions['view own field_reference_pop_other_ic'] = array(
    'name' => 'view own field_reference_pop_other_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_reference_population'.
  $permissions['view own field_reference_population'] = array(
    'name' => 'view own field_reference_population',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_release_date'.
  $permissions['view own field_release_date'] = array(
    'name' => 'view own field_release_date',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  // Exported permission: 'view own field_s_asian_mds_plots_ic'.
  $permissions['view own field_s_asian_mds_plots_ic'] = array(
    'name' => 'view own field_s_asian_mds_plots_ic',
    'roles' => array(
      'administrator' => 'administrator',
      'consortium administrator' => 'consortium administrator',
    ),
    'module' => 'field_permissions',
  );

  return $permissions;
}
